ContactsManager.UI/Controllers/CountriesController.cs
using Microsoft.AspNetCore.Mvc;
using ServiceContracts;

namespace CRUDExample.Controllers
{
 [Route("[controller]")]
 public class CountriesController : Controller
 {
  private readonly ICountriesGetterService _countriesGetterService;
  private readonly ICountriesUploaderService _countriesUploaderService;

  public CountriesController(ICountriesGetterService countriesService)
  {
   _countriesGetterService = countriesService;
  }


  [Route("UploadFromExcel")]
  public IActionResult UploadFromExcel()
  {
   return View();
  }


  [HttpPost]
  [Route("UploadFromExcel")]
  public async Task<IActionResult> UploadFromExcel(IFormFile excelFile)
  {
   if (excelFile == null || excelFile.Length == 0)
   {
    ViewBag.ErrorMessage = "Please select an xlsx file";
    return View();
   }

   if (!Path.GetExtension(excelFile.FileName).Equals(".xlsx", StringComparison.OrdinalIgnoreCase))
   {
    ViewBag.ErrorMessage = "Unsupported file. 'xlsx' file is expected";
    return View();
   }

   int countriesCountInserted = await _countriesUploaderService.UploadCountriesFromExcelFile(excelFile);

   ViewBag.Message = $"{countriesCountInserted} Countries Uploaded";
   return View();
  }
 }
}

ContactsManager.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace CRUDExample.Controllers
{
 public class HomeController : Controller
 {
  [Route("Error")]
  public IActionResult Error()
  {
   IExceptionHandlerPathFeature ? exceptionHandlerPathFeature = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
   if (exceptionHandlerPathFeature != null && exceptionHandlerPathFeature.Error != null)
   {
    ViewBag.ErrorMessage = exceptionHandlerPathFeature.Error.Message;
   }
   return View(); //Views/Shared/Error
  }
 }
}

ContactsManager.UI/Controllers/PersonsController.cs
using CRUDExample.Filters;
using CRUDExample.Filters.ActionFilters;
using CRUDExample.Filters.AuthorizationFilter;
using CRUDExample.Filters.ExceptionFilters;
using CRUDExample.Filters.ResourceFilters;
using CRUDExample.Filters.ResultFilters;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Rotativa.AspNetCore;
using ServiceContracts;
using ServiceContracts.DTO;
using ServiceContracts.Enums;

namespace CRUDExample.Controllers
{
 [Route("[controller]")]

 [ResponseHeaderFilterFactory("My-Key-From-Controller", "My-Value-From-Controller", 3)]
 //[TypeFilter(typeof(HandleExceptionFilter))]
 [TypeFilter(typeof(PersonAlwaysRunResultFilter))]
 public class PersonsController : Controller
 {
  //private fields
  private readonly IPersonsGetterService _personsGetterService;
  private readonly IPersonsAdderService _personsAdderService;
  private readonly IPersonsSorterService _personsSorterService;
  private readonly IPersonsDeleterService _personsDeleterService;
  private readonly IPersonsUpdaterService _personsUpdaterService;
  
  private readonly ICountriesGetterService _countriesGetterService;
  private readonly ILogger<PersonsController> _logger;

  //constructor
  public PersonsController(IPersonsGetterService personsGetterService, IPersonsAdderService personsAdderService, IPersonsDeleterService personsDeleterService, IPersonsUpdaterService personsUpdaterService, IPersonsSorterService personsSorterService, ICountriesGetterService countriesService, ILogger<PersonsController> logger)
  {
   _personsGetterService = personsGetterService;
   _personsAdderService = personsAdderService;
   _personsUpdaterService = personsUpdaterService;
   _personsDeleterService = personsDeleterService;
   _personsSorterService = personsSorterService;

   _countriesGetterService = countriesService;
   _logger = logger;
  }

  //Url: persons/index
  [Route("[action]")]
  [Route("/")]
  [ServiceFilter(typeof(PersonsListActionFilter), Order = 4)]

  [ResponseHeaderFilterFactory("MyKey-FromAction", "MyValue-From-Action", 1)]

  [TypeFilter(typeof(PersonsListResultFilter))]
  [SkipFilter]
  public async Task<IActionResult> Index(string searchBy, string? searchString, string sortBy = nameof(PersonResponse.PersonName), SortOrderOptions sortOrder = SortOrderOptions.ASC)
  {
   _logger.LogInformation("Index action method of PersonsController");

   _logger.LogDebug($"searchBy: {searchBy}, searchString: {searchString}, sortBy: {sortBy}, sortOrder: {sortOrder}");


   //Search
   List<PersonResponse> persons = await _personsGetterService.GetFilteredPersons(searchBy, searchString);

   //Sort
   List<PersonResponse> sortedPersons = await _personsSorterService.GetSortedPersons(persons, sortBy, sortOrder);

   return View(sortedPersons); //Views/Persons/Index.cshtml
  }


  //Executes when the user clicks on "Create Person" hyperlink (while opening the create view)
  //Url: persons/create
  [Route("[action]")]
  [HttpGet]
  [ResponseHeaderFilterFactory("my-key", "my-value", 4)]
  public async Task<IActionResult> Create()
  {
   List<CountryResponse> countries = await _countriesGetterService.GetAllCountries();
   ViewBag.Countries = countries.Select(temp =>
     new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() }
   );

   //new SelectListItem() { Text="Harsha", Value="1" }
   //<option value="1">Harsha</option>
   return View();
  }


  [HttpPost]
  //Url: persons/create
  [Route("[action]")]
  [TypeFilter(typeof(PersonCreateAndEditPostActionFilter))]
  [TypeFilter(typeof(FeatureDisabledResourceFilter), Arguments = new object[] {  false })]
  public async Task<IActionResult> Create(PersonAddRequest personRequest)
  {
   //call the service method
   PersonResponse personResponse = await _personsAdderService.AddPerson(personRequest);

   //navigate to Index() action method (it makes another get request to "persons/index"
   return RedirectToAction("Index", "Persons");
  }


  [HttpGet]
  [Route("[action]/{personID}")] //Eg: /persons/edit/1
  [TypeFilter(typeof(TokenResultFilter))]
  public async Task<IActionResult> Edit(Guid personID)
  {
   PersonResponse? personResponse = await _personsGetterService.GetPersonByPersonID(personID);
   if (personResponse == null)
   {
    return RedirectToAction("Index");
   }

   PersonUpdateRequest personUpdateRequest = personResponse.ToPersonUpdateRequest();

   List<CountryResponse> countries = await _countriesGetterService.GetAllCountries();
   ViewBag.Countries = countries.Select(temp =>
   new SelectListItem() { Text = temp.CountryName, Value = temp.CountryID.ToString() });

   return View(personUpdateRequest);
  }


  [HttpPost]
  [Route("[action]/{personID}")]
  [TypeFilter(typeof(PersonCreateAndEditPostActionFilter))]
  [TypeFilter(typeof(TokenAuthorizationFilter))]
  public async Task<IActionResult> Edit(PersonUpdateRequest personRequest)
  {
   PersonResponse? personResponse = await _personsGetterService.GetPersonByPersonID(personRequest.PersonID);

   if (personResponse == null)
   {
    return RedirectToAction("Index");
   }

   PersonResponse updatedPerson = await _personsUpdaterService.UpdatePerson(personRequest);
   return RedirectToAction("Index");
  }


  [HttpGet]
  [Route("[action]/{personID}")]
  public async Task<IActionResult> Delete(Guid? personID)
  {
   PersonResponse? personResponse = await _personsGetterService.GetPersonByPersonID(personID);
   if (personResponse == null)
    return RedirectToAction("Index");

   return View(personResponse);
  }

  [HttpPost]
  [Route("[action]/{personID}")]
  public async Task<IActionResult> Delete(PersonUpdateRequest personUpdateResult)
  {
   PersonResponse? personResponse = await _personsGetterService.GetPersonByPersonID(personUpdateResult.PersonID);
   if (personResponse == null)
    return RedirectToAction("Index");

   await _personsDeleterService.DeletePerson(personUpdateResult.PersonID);
   return RedirectToAction("Index");
  }


  [Route("PersonsPDF")]
  public async Task<IActionResult> PersonsPDF()
  {
   //Get list of persons
   List<PersonResponse> persons = await _personsGetterService.GetAllPersons();

   //Return view as pdf
   return new ViewAsPdf("PersonsPDF", persons, ViewData)
   {
    PageMargins = new Rotativa.AspNetCore.Options.Margins() { Top = 20, Right = 20, Bottom = 20, Left = 20 },
    PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
   };
  }


  [Route("PersonsCSV")]
  public async Task<IActionResult> PersonsCSV()
  {
   MemoryStream memoryStream = await _personsGetterService.GetPersonsCSV();
   return File(memoryStream, "application/octet-stream", "persons.csv");
  }


  [Route("PersonsExcel")]
  public async Task<IActionResult> PersonsExcel()
  {
   MemoryStream memoryStream = await _personsGetterService.GetPersonsExcel();
   return File(memoryStream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "persons.xlsx");
  }
 }
}

ContactsManager.UI/Views/Countries/UploadFromExcel.cshtml
@{
 ViewBag.Title = "Upload Countries from Excel";
}

<!-- breadcrumb starts -->
<div class="flex">
 <div class="flex-1">
  <div class="text-grey">
   <span>Contacts</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Countries</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Upload</span>
  </div>
 </div>
</div>
<!-- breadcrumb ends -->



<div class="form-container">

 <h2 class="text-large">Upload Countries from Excel</h2>

 <form asp-action="UploadFromExcel" asp-controller="Countries" method="post" enctype="multipart/form-data">

  @* ExcelFile *@
  <div class="form-field flex">
   <div class="w-25">
    <label class="form-label pt">Choose an xlsx file</label>
   </div>
   <div class="flex-1">
    <input type="file" name="excelFile" class="form-input" />
    <div class="text-red">@ViewBag.ErrorMessage</div>
    <div class="text-green">@ViewBag.Message</div>
   </div>
  </div>

  <div class="form-field flex">
   <div class="w-25"></div>
   <div class="flex-1">
    <button type="submit" class="button button-green-back">Upload</button>
   </div>
  </div>

 </form>

</div>

ContactsManager.UI/Views/Persons/Create.cshtml
@model PersonAddRequest

@{
 ViewBag.Title = "Create Person";
}

<!-- breadcrumb starts -->
<div class="flex">
 <div class="flex-1">
  <div class="text-grey">
   <span>Contacts</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Persons</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Create</span>
  </div>
 </div>
</div>
<!-- breadcrumb ends -->



<div class="form-container">

    <a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
<h2 class="text-large">Create Person</h2>

 <form asp-controller="Persons" asp-action="Create" method="post">

  @*PersonName*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="PersonName" class="form-label pt">Person Name</label>
   </div>
   <div class="flex-1">
    <input asp-for="PersonName" class="form-input" />
    <span asp-validation-for="PersonName" class="text-red"></span>
   </div>
  </div>


  @*Email*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="Email" class="form-label pt">Email</label>
   </div>
   <div class="flex-1">
    <input asp-for="Email" class="form-input" />
    <span asp-validation-for="Email" class="text-red"></span>
   </div>
  </div>

  @*DateOfBirth*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="DateOfBirth" class="form-label pt">Date of Birth</label>
   </div>
   <div class="flex-1">
    <input type="date" asp-for="DateOfBirth" class="form-input" />
    <span asp-validation-for="DateOfBirth" class="text-red"></span>
   </div>
  </div>

  @*Gender*@
  <div class="form-field flex">
   <div class="w-25">
    <label class="form-label">Gender</label>
   </div>
   <div class="flex-1">
    @{
     string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
    }
    @foreach (string gender in genders)
    {
     <input type="radio" asp-for="Gender" value="@gender" id="@gender" />
     <label for="@gender">@gender</label>
    }
    <span asp-validation-for="Gender" class="text-red"></span>
   </div>
  </div>

  @*Country*@
  <div class="form-field flex">
   <div class="w-25">
    <label class="form-label" asp-for="CountryID">Country</label>
   </div>
   <div class="flex-1">
    <select asp-for="CountryID" class="form-input" asp-items="@ViewBag.Countries">
     <option value="">Please Select</option>
    </select>
    <span asp-validation-for="CountryID" class="text-red"></span>
   </div>
  </div>


  @*Address*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="Address" class="form-label pt">Address</label>
   </div>
   <div class="flex-1">
    <textarea asp-for="Address" class="form-input"></textarea>
    <span asp-validation-for="Address" class="text-red"></span>
   </div>
  </div>

  @*ReceiveNewsLetters*@
  <div class="form-field flex">
   <div class="w-25">
   </div>
   <div class="flex-1">
    <input asp-for="ReceiveNewsLetters" value="true" />
    <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
    <span asp-validation-for="ReceiveNewsLetters" class="text-red"></span>
   </div>
  </div>

  @*Submit*@
  <div class="form-field flex">
   <div class="w-25">
   </div>
   <div class="flex-1">
    <button class="button button-green-back">Create</button>

    <div asp-validation-summary="All" class="text-red"></div>

    @if (ViewBag.Errors != null)
    {
     <div class="text-red ml">
      <ul>
       @foreach (string error in ViewBag.Errors)
       {
        <li class="ml">@error</li>
       }
      </ul>
     </div>
    }
   </div>
  </div>

 </form>
</div>

@section scripts
 {
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>

 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min.js"></script>

 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="~/jquery.validate.unobtrusive.min.js"></script>
}

ContactsManager.UI/Views/Persons/Delete.cshtml
@model PersonResponse

@{
 ViewBag.Title = "Delete Person";
}


<!-- breadcrumb starts -->
<div class="flex">
 <div class="flex-1">
  <div class="text-grey">
   <span>Contacts</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Persons</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Delete</span>
  </div>
 </div>
</div>
<!-- breadcrumb ends -->



<div class="form-container">

 <a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
 <h2 class="text-large">Delete Person</h2>
 <h3>Are you sure to delete this person?</h3>

 <form asp-controller="Persons" asp-action="Delete" method="post">

  <input type="hidden" asp-for="PersonID" />

  @*PersonName*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="PersonName" class="form-label pt">Person Name</label>
   </div>
   <div class="flex-1">
    <input asp-for="PersonName" class="form-input" disabled="disabled" />
    <span asp-validation-for="PersonName" class="text-red"></span>
   </div>
  </div>


  @*Email*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="Email" class="form-label pt">Email</label>
   </div>
   <div class="flex-1">
    <input asp-for="Email" class="form-input" disabled="disabled" />
    <span asp-validation-for="Email" class="text-red"></span>
   </div>
  </div>


  @*Submit*@
  <div class="form-field flex">
   <div class="w-25">
   </div>
   <div class="flex-1">
    <button class="button button-red-back">Delete</button>

    <div asp-validation-summary="All" class="text-red"></div>

    @if (ViewBag.Errors != null)
    {
     <div class="text-red ml">
      <ul>
       @foreach (string error in ViewBag.Errors)
       {
        <li class="ml">@error</li>
       }
      </ul>
     </div>
    }
   </div>
  </div>

 </form>
</div>

ContactsManager.UI/Views/Persons/Edit.cshtml
@model PersonUpdateRequest

@{
 ViewBag.Title = "Edit Person";
}

<!-- breadcrumb starts -->
<div class="flex">
 <div class="flex-1">
  <div class="text-grey">
   <span>Contacts</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Persons</span>
   <i class="fa-solid fa-caret-right"></i>
   <span class="text-grey">Edit</span>
  </div>
 </div>
</div>
<!-- breadcrumb ends -->



<div class="form-container">
 <a asp-controller="Persons" asp-action="Index" class="link-hover">Back to Persons List</a>
 <h2 class="text-large">Edit Person</h2>

 <form asp-controller="Persons" asp-action="Edit" method="post">

  <input type="hidden" asp-for="PersonID" />

  @*PersonName*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="PersonName" class="form-label pt">Person Name</label>
   </div>
   <div class="flex-1">
    <input asp-for="PersonName" class="form-input" />
    <span asp-validation-for="PersonName" class="text-red"></span>
   </div>
  </div>


  @*Email*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="Email" class="form-label pt">Email</label>
   </div>
   <div class="flex-1">
    <input asp-for="Email" class="form-input" />
    <span asp-validation-for="Email" class="text-red"></span>
   </div>
  </div>

  @*DateOfBirth*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="DateOfBirth" class="form-label pt">Date of Birth</label>
   </div>
   <div class="flex-1">
    <input type="date" asp-for="DateOfBirth" class="form-input" />
    <span asp-validation-for="DateOfBirth" class="text-red"></span>
   </div>
  </div>

  @*Gender*@
  <div class="form-field flex">
   <div class="w-25">
    <label class="form-label">Gender</label>
   </div>
   <div class="flex-1">
    @{
     string[] genders = (string[])Enum.GetNames(typeof(GenderOptions));
    }
    @foreach (string gender in genders)
    {
     <input type="radio" asp-for="Gender" value="@gender" id="@gender" />
     <label for="@gender">@gender</label>
    }
    <span asp-validation-for="Gender" class="text-red"></span>
   </div>
  </div>

  @*Country*@
  <div class="form-field flex">
   <div class="w-25">
    <label class="form-label" asp-for="CountryID">Country</label>
   </div>
   <div class="flex-1">
    <select asp-for="CountryID" class="form-input" asp-items="@ViewBag.Countries">
     <option value="">Please Select</option>
    </select>
    <span asp-validation-for="CountryID" class="text-red"></span>
   </div>
  </div>


  @*Address*@
  <div class="form-field flex">
   <div class="w-25">
    <label asp-for="Address" class="form-label pt">Address</label>
   </div>
   <div class="flex-1">
    <textarea asp-for="Address" class="form-input"></textarea>
    <span asp-validation-for="Address" class="text-red"></span>
   </div>
  </div>

  @*ReceiveNewsLetters*@
  <div class="form-field flex">
   <div class="w-25">
   </div>
   <div class="flex-1">
    <input asp-for="ReceiveNewsLetters" value="true" />
    <label asp-for="ReceiveNewsLetters" class="form-label">Receive News Letters</label>
    <span asp-validation-for="ReceiveNewsLetters" class="text-red"></span>
   </div>
  </div>

  @*Submit*@
  <div class="form-field flex">
   <div class="w-25">
   </div>
   <div class="flex-1">
    <button class="button button-green-back">Update</button>

    <div asp-validation-summary="All" class="text-red"></div>

    @if (ViewBag.Errors != null)
    {
     <div class="text-red ml">
      <ul>
       @foreach (string error in ViewBag.Errors)
       {
        <li class="ml">@error</li>
       }
      </ul>
     </div>
    }
   </div>
  </div>

 </form>
</div>

@section scripts
 {
 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" asp-fallback-test="window.jQuery" asp-fallback-src="~/jquery.min.js"></script>

 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.4/jquery.validate.min.js" asp-fallback-test="window.jQuery.validator" asp-fallback-src="~/jquery.validate.min.js"></script>

 <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.12/jquery.validate.unobtrusive.min.js" asp-fallback-test="window.jQuery.validator.unobstrusive" asp-fallback-src="~/jquery.validate.unobtrusive.min.js"></script>
}

ContactsManager.UI/Views/Persons/PersonsPDF.cshtml
@model IEnumerable<PersonResponse>

@{
    Layout = null;
}

<link href="@("http://" + Context.Request.Host.ToString() + "/Stylesheet.css")" rel="stylesheet" />
@* http://localhost:port/StyleSheet.css *@

<h1>Persons</h1>

<table class="table w-100 mt">
    <thead>
        <tr>
            <th>Person Name</th>
            <th>Email</th>
            <th>Date of Birth</th>
            <th>Age</th>
            <th>Gender</th>
            <th>Country</th>
            <th>Address</th>
            <th>Receive News Letters</th>
        </tr>
    </thead>
    <tbody>
        @foreach (PersonResponse person in Model)
        {
            <tr>
                <td style="width:15%">@person.PersonName</td>
                <td style="width:20%">@person.Email</td>
                <td style="width:13%">@person.DateOfBirth?.ToString("dd MMM yyyy")</td>
                <td style="width:9%">@person.Age</td>
                <td style="width:9%">@person.Gender</td>
                <td style="width:10%">@person.Country</td>
                <td style="width:15%">@person.Address</td>
                <td style="width:20%">@person.ReceiveNewsLetters</td>
            </tr>
        }
    </tbody>

</table>

ContactsManager.UI/Views/Shared/_GridColumnHeader.cshtml
@if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderOptions.ASC.ToString())
{
 <th>
  <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(nameof(SortOrderOptions.DESC))">@(ViewBag.DisplayName)</a>
  <i class="fa-solid fa-sort-up"></i>
 </th>
}
else if (ViewBag.CurrentSortBy == ViewBag.ColumnName && ViewBag.CurrentSortOrder == SortOrderOptions.DESC.ToString())
{
 <th>
  <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(nameof(SortOrderOptions.ASC))">@(ViewBag.DisplayName)</a>
  <i class="fa-solid fa-sort-down"></i>
 </th>
}
else
{
 <th>
  <a href="~/persons/index?searchBy=@(ViewBag.CurrentSearchBy)&searchString=@(ViewBag.CurrentSearchString)&sortBy=@(ViewBag.ColumnName)&sortOrder=@(nameof(SortOrderOptions.ASC))">@ViewBag.DisplayName</a>
 </th>
}

ContactsManager.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
 <meta name="viewport" content="width=device-width" />
 <title>@ViewBag.Title</title>
 <link href="~/Stylesheet.css" rel="stylesheet" />

 <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g==" crossorigin="anonymous" referrerpolicy="no-referrer" />

</head>
<body>
 <div class="container">
  <div class="page-content">

   <div class="margin-bottom">
    <div class="flex" id="top-bar-div">
     <div class="flex-1" id="app-title-div">
      <h1 class="app-title">
       <i class="fa-solid fa-people-simple"></i>
       Contacts Manager
      </h1>
     </div>


     <div class="flex-1 pr" id="search-box-div">
      <div class="navbar account-links">

       <ul>
        <li>
         <a asp-controller="Account" asp-action="Register">Register</a>
         <a asp-controller="Account" asp-action="Login">Login</a>
        </li>
       </ul>
      </div>

     </div>
    </div>

   </div>


   <div class="navbar mb">
    
    <ul>
     <li>
      <a asp-controller="Persons" asp-action="Index">Persons</a>
      <a asp-controller="Countries" asp-action="UploadFromExcel">Upload Countries</a>
     </li>
    </ul>
   </div>

   <div class="body">
    @RenderBody()
   </div>
  </div>
 </div>

 @RenderSection("scripts", required: false)
</body>
</html>